### ISSUE TITLE
fldname

### ISSUE THREAD

**Issue by kknierim-usgs** [brclark-usgs/zonepy#1]
There is non-parallel code btw stats and category functions if your fldname is left as the default none. We also need to deal with using fldid if user doesn't supply fldname. Example, fails at line ~330 when creating dictionary (because fldname is None). May be able to change fldname to fldid...?

**Comment by brclark-usgs** [comment]
added code to help deal with fldname == None. may need testing.

**Comment by brclark-usgs** [comment]
looks like commit a2f3fc616f8070f5413af52ca7c3fe62482ace38 fixes this.
