### ISSUE TITLE
no data value error

### ISSUE THREAD

**Issue by kknierim-usgs** [brclark-usgs/zonepy#13]
When using compute_stats() method there is an odd error if a point falls within the raster extent but is 100 % no data. Note that this issue occurs specifically with no data values generated by ArcMAP (which become a large negative number, i.e., -3.4028235e+38). Oddly, if the no data value occurs within the mDict with other values (e.g., {-3.4028235e+38: 28, 1.100047: 3, 1.508: 46, 1.516509: 20}) then nd (no data) is calculated correctly. If the no data value is the only key in mDict (e.g., {-3.402823e+38: 42}) then nd is not calculated (remains zero because nd = 0 is set a few lines above). I cannot figure out why a single key dictionary won't work...  the code fails when it checks: `if self.__orig_nodata in keys`

**Comment by brclark-usgs** [comment]
what is the error?
Is there a small raster that will duplicate the issue?

**Comment by kknierim-usgs** [comment]
The code doesn't actually error... it just doesn't correctly enter the loop on line 506.

I've got a raster that will work for testing... will try to load it into the repo

**Comment by kknierim-usgs** [comment]
I'm wondering if this is something related to the issue: https://stackoverflow.com/questions/7559595/python-runtimewarning-overflow-encountered-in-long-scalars

**Comment by kknierim-usgs** [comment]
One other odd note... I am trying to recreate the problem with another raster (which also has the large negative no data value), and the behavior isn't consistent between the two rasters. I'm trying to pinpoint if there is something different between the two rasters to cause the issue.

**Comment by kknierim-usgs** [comment]
Update: for some reason, the no data value in the example raster is evaluated by python as negative INF. Again, not sure why behavior is intermittent.

**Comment by kknierim-usgs** [comment]
added a flag for arc no data values via commit b7a26d4ec06c7037ada445a781e3c7f94db8d994, and handle the values as -9999
