### ISSUE TITLE
buffer of points

### ISSUE THREAD

**Issue by kknierim-usgs** [brclark-usgs/zonepy#3]
If using well points with 0 buffer, need separate code to do simple extraction (instead of resampling with zoom)

**Comment by brclark-usgs** [comment]
added draft extract by point in 00d938aeab3984d98042a8bd09741e9cbb79807f. 
also noticed that when buffer == 0, there still seems to be some buffer applied (maybe tiny?) - but adjusted in 87645cf64a2bcabb88fd5581a4f0671e98323aec to add a small negative buffer. hack, but need to look further.

**Comment by kknierim-usgs** [comment]
I think we can close this. Tested a point dataset with 0 buffer, and the "error message" came up fine.
